-- ==============================
-- PostgreSQL DDL Conversion
-- ==============================

-- prm_tdb_objets
CREATE TABLE IF NOT EXISTS prm_tdb_objets (
idObjet SERIAL PRIMARY KEY,
RAPPR_CODE VARCHAR(200) NOT NULL,
PAGE_CODE VARCHAR(200) NOT NULL,
OBJT_CODE VARCHAR(200) NOT NULL,
OBJT_TYPE VARCHAR(200) NOT NULL,
OBJT_LIBL VARCHAR(200) NOT NULL,
TITRE_OBJET VARCHAR(200) NOT NULL
);

-- prm_rows
CREATE TABLE IF NOT EXISTS prm_rows (
idRows SERIAL PRIMARY KEY,
idObjet INT REFERENCES prm_tdb_objets(idObjet) ON DELETE CASCADE,
ROWS_CODE VARCHAR(200) DEFAULT NULL,
ROWS_NIV VARCHAR(200) DEFAULT '0',
ROWS_ORDR VARCHAR(200) DEFAULT '0'
);

-- prm_cols_calcul
CREATE TABLE IF NOT EXISTS prm_cols_calcul (
CALC_CODE VARCHAR(200) PRIMARY KEY,
CALC_FORMULE VARCHAR(200) DEFAULT NULL,
CALC_FAMILLE VARCHAR(200) DEFAULT NULL,
CALC_TYPE VARCHAR(200) DEFAULT NULL
);

-- prm_cols
CREATE TABLE IF NOT EXISTS prm_cols (
idCols SERIAL PRIMARY KEY,
idObjet INT REFERENCES prm_tdb_objets(idObjet) ON DELETE CASCADE,
COLS_CODE VARCHAR(200) DEFAULT NULL,
COLS_ENTETE1 VARCHAR(200) DEFAULT NULL,
COLS_ENTETE2 VARCHAR(200) DEFAULT NULL,
COLS_ENTETE3 VARCHAR(200) DEFAULT NULL,
COLS_FORMAT VARCHAR(200) DEFAULT NULL,
COLS_PRM_GRAPHE VARCHAR(200) DEFAULT NULL,
COLS_LIBL VARCHAR(200) DEFAULT NULL,
COLS_COEF VARCHAR(200) DEFAULT NULL,
COLS_NATURE VARCHAR(200) DEFAULT NULL,
COLS_DATAMART VARCHAR(200) DEFAULT NULL,
COLS_FORMULE VARCHAR(200),
COLS_ORDRE INT DEFAULT 0
);

-- prm_cols_filtre
CREATE TABLE IF NOT EXISTS prm_cols_filtre (
idObjet INT REFERENCES prm_tdb_objets(idObjet) ON DELETE CASCADE,
idCols INT NOT NULL,
COLS_CODE VARCHAR(10) NOT NULL,
COLS_FILTRE_DOMAINE VARCHAR(10) NOT NULL,
DIM_CODE VARCHAR(10) NOT NULL,
DIM_VAL_CODE VARCHAR(10) NOT NULL,
FILTRE_TAB VARCHAR(60) NOT NULL,
FILTRE_CHA VARCHAR(60) NOT NULL,
FILTRE_VAL VARCHAR(60) NOT NULL,
FILTRE_SENS VARCHAR(10) NOT NULL,
PRIMARY KEY (idCols, FILTRE_CHA, FILTRE_VAL)
);

-- dmrc_fact
CREATE TABLE IF NOT EXISTS dmrc_fact (
idCols INT NOT NULL REFERENCES prm_cols(idCols) ON DELETE CASCADE,
idRows INT NOT NULL REFERENCES prm_rows(idRows) ON DELETE CASCADE,
idObjet INT NOT NULL REFERENCES prm_tdb_objets(idObjet) ON DELETE CASCADE,
DAR_REF VARCHAR(10) NOT NULL,
idFACTLigne INT,
PERD VARCHAR(10) DEFAULT NULL,
COLS_CODE VARCHAR(10) DEFAULT NULL,
ROWS_CODE VARCHAR(10) DEFAULT NULL,
idSQLLigne VARCHAR(200),
PERIMETRE VARCHAR(10) DEFAULT NULL,
VALEUR VARCHAR(200) DEFAULT NULL,
STATUS VARCHAR(200) DEFAULT NULL,
MSG VARCHAR(200) DEFAULT 'GOOD',
LIEN_INVALIDE VARCHAR(200) DEFAULT 'GOOD',
FORMULE VARCHAR(200) DEFAULT NULL,
FORMULE_VALORISE VARCHAR(200) DEFAULT NULL,
FORMULE_REF VARCHAR(200) DEFAULT NULL,
DATE_TRT VARCHAR(200) DEFAULT NULL,
PRIMARY KEY (idCols, idRows, idObjet, DAR_REF)
);

-- dmrc_ref_sql
CREATE TABLE IF NOT EXISTS dmrc_ref_sql (
idCol INT NOT NULL,
idRow INT NOT NULL,
idObjet INT NOT NULL REFERENCES prm_tdb_objets(idObjet) ON DELETE CASCADE,
DAR_REF VARCHAR(10) NOT NULL,
idSQLLigne INT UNIQUE,
PERD VARCHAR(10) DEFAULT NULL,
COLS_CODE VARCHAR(10) DEFAULT NULL,
ROWS_CODE VARCHAR(10) DEFAULT NULL,
SQL_CODE_SRC VARCHAR(1000) DEFAULT NULL,
SQL_CODE_FINAL VARCHAR(1000) DEFAULT NULL,
PERIMETRE VARCHAR(10) DEFAULT NULL,
DATE_TRT VARCHAR(200) DEFAULT NULL,
NIV VARCHAR(200) DEFAULT '0',
PRIMARY KEY (idCol, idRow, idObjet, DAR_REF)
);

-- prm_rows_filtre
CREATE TABLE IF NOT EXISTS prm_rows_filtre (
idObjet INT REFERENCES prm_tdb_objets(idObjet) ON DELETE CASCADE,
idRows INT NOT NULL,
ROWS_CODE VARCHAR(10) NOT NULL,
DIM_CODE VARCHAR(10) NOT NULL,
DIM_VAL_CODE VARCHAR(10) NOT NULL,
FILTRE_TAB VARCHAR(60) NOT NULL,
FILTRE_CHA VARCHAR(60) NOT NULL,
FILTRE_VAL VARCHAR(60) NOT NULL,
FILTRE_SENS VARCHAR(10) NOT NULL,
PRIMARY KEY (idRows, FILTRE_CHA, FILTRE_VAL)
);

-- prm_sql_model
CREATE TABLE IF NOT EXISTS prm_sql_model (
idSQL SERIAL PRIMARY KEY,
INDI_CODE_SQL VARCHAR(100) NOT NULL,
CODE_SQL VARCHAR(10) NOT NULL,
TEXT_SQL VARCHAR(1000) NOT NULL
);

-- vw_cube_dplt_icare_bpce_encr
CREATE TABLE IF NOT EXISTS vw_cube_dplt_icare_bpce_encr (
        id VARCHAR(255) PRIMARY KEY,
        PERD_ARRT_INFO VARCHAR(255),
        DATE_TRT VARCHAR(255),
        CODE_ORGN_FINN VARCHAR(255),
        CODE_INDIC_REQT VARCHAR(255),
        CODE_PRDT_ICARE VARCHAR(255),
        CODE_MARC_ICARE VARCHAR(255),
        CODE_PHAS_ICARE VARCHAR(255),
        LIBL_SOUR_ICARE VARCHAR(255),
        MT_VERST VARCHAR(255),
        MT_REMB VARCHAR(255),
        MT_ENCR_DEVS VARCHAR(255),
        MT_ENCR_MOYE VARCHAR(255),
        MT_ENGG VARCHAR(255),
        NB_OUVR VARCHAR(255),
        NB_FERM VARCHAR(255),
        NB_STCK_CONT VARCHAR(255),
        MT_EXCDT VARCHAR(255),
        MT_VENT_NET VARCHAR(255),
        MT_ENCR_MOYE_MARC VARCHAR(255),
        MT_COMM VARCHAR(255),
        MT_COMM_APPR VARCHAR(255),
        MT_COMM_RISQ VARCHAR(255),
        MT_SURC VARCHAR(255),
        MT_COMM_ENCR VARCHAR(255),
        MT_COMM_VERST VARCHAR(255),
        MT_FRS VARCHAR(255),
        TX_FRS VARCHAR(255),
        TX_COMM VARCHAR(255),
        MT_ENCR_MOYE_CUML VARCHAR(255),
        MT_EXCDT_MENS VARCHAR(255),
        NB_VENT_NET_MENS VARCHAR(255),
        MT_VART_STCK VARCHAR(255),
        MT_VART_STCK_CUML VARCHAR(255),
        MT_ENGG_MENS VARCHAR(255),
        MT_ENCR_MENS VARCHAR(255),
        MT_ENCR_VART VARCHAR(255),
        CODE_PRVN VARCHAR(255),
        LIBL_INDIC_REQT VARCHAR(255),
        FAMI_INDIC_REQT VARCHAR(255),
        LIBL_MARC_ICARE VARCHAR(255),
        C_NIV_1 VARCHAR(255),
        L_NIV_1 VARCHAR(255),
        C_NIV_2 VARCHAR(255),
        L_NIV_2 VARCHAR(255),
        C_NIV_3 VARCHAR(255),
        L_NIV_3 VARCHAR(255),
        C_NIV_4 VARCHAR(255),
        L_NIV_4 VARCHAR(255),
        C_NIV_41 VARCHAR(255),
        L_NIV_41 VARCHAR(255),
        CODE_NIV0_ICARE VARCHAR(255),
        LIBL_NIV0_ICARE VARCHAR(255),
        CODE_NIV1_ICARE VARCHAR(255),
        LIBL_NIV1_ICARE VARCHAR(255),
        CODE_NIV2_ICARE VARCHAR(255),
        LIBL_NIV2_ICARE VARCHAR(255),
        CODE_NIV3_ICARE VARCHAR(255),
        LIBL_NIV3_ICARE VARCHAR(255),
        CODE_NIV4_ICARE VARCHAR(255),
        LIBL_NIV4_ICARE VARCHAR(255)
);

-- vw_cube_vbpce_apc_faits
CREATE TABLE IF NOT EXISTS vw_cube_vbpce_apc_faits (
   id VARCHAR(255) PRIMARY KEY,
   PERD_ARRT_INFO VARCHAR(255),
   DATE_TRT VARCHAR(255),
   CODE_ORGN_FINN VARCHAR(255),
   CODE_PRDT_ICARE VARCHAR(255),
   CODE_MARC_ICARE VARCHAR(255),
   LIBL_SOUR VARCHAR(255),
   CODE_INDC VARCHAR(255),
   FREQUENCE VARCHAR(255),
   NUMR_SEMN VARCHAR(255),
   VALR_INDC VARCHAR(255),
   C_NIV_1 VARCHAR(255),
   C_NIV_2 VARCHAR(255),
   C_NIV_3 VARCHAR(255),
   C_NIV_4 VARCHAR(255),
   C_NIV_41 VARCHAR(255),
   CODE_GROUPE_SOURCE VARCHAR(255),
   CODE_TYPE_SOURCE VARCHAR(255),
   CODE_SOURCE VARCHAR(255),
   CODE_NIV3_APC VARCHAR(255),
   CODE_NIV2_APC VARCHAR(255)
);

-- prm_cols_composant
CREATE TABLE IF NOT EXISTS prm_cols_composant (
idRaComp SERIAL PRIMARY KEY,
idObjetSrc INT REFERENCES prm_tdb_objets(idObjet) ON DELETE CASCADE,
idObjetCib INT REFERENCES prm_tdb_objets(idObjet) ON DELETE CASCADE,
idColscib INT REFERENCES prm_cols(idCols) ON DELETE CASCADE,
COLS_CODE VARCHAR(200) DEFAULT NULL,
CODE_COMPOSANT VARCHAR(200) DEFAULT NULL,
idColsSrc INT REFERENCES prm_cols(idCols) ON DELETE CASCADE,
COLS_CODE_SRC VARCHAR(200) DEFAULT NULL
);

-- dmrc_lineage
CREATE TABLE IF NOT EXISTS dmrc_lineage (
idCols INT REFERENCES prm_cols(idCols) ON DELETE CASCADE,
idRows INT REFERENCES prm_rows(idRows) ON DELETE CASCADE,
Value INT,
Origine VARCHAR(200),
Formule_valo VARCHAR(200),
liste_composants VARCHAR(200)
);

-- dmrc_lineage_final
CREATE TABLE IF NOT EXISTS dmrc_lineage_final (
id SERIAL PRIMARY KEY,
idCols INT REFERENCES prm_cols(idCols) ON DELETE CASCADE,
idRows INT REFERENCES prm_rows(idRows) ON DELETE CASCADE,
Value INT,
Origine VARCHAR(200),
Formule_valo VARCHAR(200),
liste_composants VARCHAR(200)
);